
package com.woolpert.safe.webservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SafeImpl", targetNamespace = "http://webservices.safe.woolpert.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SafeImpl {


    /**
     * 
     * @return
     *     returns java.util.List<com.woolpert.safe.webservices.Collection>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCollections", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetCollections")
    @ResponseWrapper(localName = "getCollectionsResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetCollectionsResponse")
    public List<Collection> getCollections();

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertCollection", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertCollection")
    @ResponseWrapper(localName = "insertCollectionResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertCollectionResponse")
    public ReturnStatus insertCollection(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        double arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        double arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        double arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        long arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        long arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        int arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        int arg9);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCollection", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdateCollection")
    @ResponseWrapper(localName = "updateCollectionResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdateCollectionResponse")
    public ReturnStatus updateCollection(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        double arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        double arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        double arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        double arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        long arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        long arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        int arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        int arg10);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCollections", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeleteCollections")
    @ResponseWrapper(localName = "deleteCollectionsResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeleteCollectionsResponse")
    public ReturnStatus deleteCollections(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.woolpert.safe.webservices.Asset>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAssets", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetAssets")
    @ResponseWrapper(localName = "getAssetsResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetAssetsResponse")
    public List<Asset> getAssets();

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertAsset", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertAsset")
    @ResponseWrapper(localName = "insertAssetResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertAssetResponse")
    public ReturnStatus insertAsset(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        double arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        double arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        double arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        long arg7);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @param arg8
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateAsset", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdateAsset")
    @ResponseWrapper(localName = "updateAssetResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdateAssetResponse")
    public ReturnStatus updateAsset(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        double arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        double arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        double arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        int arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        long arg8);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAsset", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeleteAsset")
    @ResponseWrapper(localName = "deleteAssetResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeleteAssetResponse")
    public ReturnStatus deleteAsset(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.woolpert.safe.webservices.Platform>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPlatforms", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetPlatforms")
    @ResponseWrapper(localName = "getPlatformsResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetPlatformsResponse")
    public List<Platform> getPlatforms();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePlatform", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdatePlatform")
    @ResponseWrapper(localName = "updatePlatformResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdatePlatformResponse")
    public ReturnStatus updatePlatform(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Boolean arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePlatform", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeletePlatform")
    @ResponseWrapper(localName = "deletePlatformResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeletePlatformResponse")
    public ReturnStatus deletePlatform(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertPlatform", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertPlatform")
    @ResponseWrapper(localName = "insertPlatformResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertPlatformResponse")
    public ReturnStatus insertPlatform(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Boolean arg2);

    /**
     * 
     * @return
     *     returns java.util.List<com.woolpert.safe.webservices.Poc>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPOCs", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetPOCs")
    @ResponseWrapper(localName = "getPOCsResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetPOCsResponse")
    public List<Poc> getPOCs();

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertPOC", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertPOC")
    @ResponseWrapper(localName = "insertPOCResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertPOCResponse")
    public ReturnStatus insertPOC(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePOC", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdatePOC")
    @ResponseWrapper(localName = "updatePOCResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdatePOCResponse")
    public ReturnStatus updatePOC(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePOC", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeletePOC")
    @ResponseWrapper(localName = "deletePOCResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeletePOCResponse")
    public ReturnStatus deletePOC(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.woolpert.safe.webservices.Organization>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrganizations", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetOrganizations")
    @ResponseWrapper(localName = "getOrganizationsResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetOrganizationsResponse")
    public List<Organization> getOrganizations();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertOrganization", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertOrganization")
    @ResponseWrapper(localName = "insertOrganizationResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertOrganizationResponse")
    public ReturnStatus insertOrganization(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateOrganization", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdateOrganization")
    @ResponseWrapper(localName = "updateOrganizationResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdateOrganizationResponse")
    public ReturnStatus updateOrganization(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteOrganization", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeleteOrganization")
    @ResponseWrapper(localName = "deleteOrganizationResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeleteOrganizationResponse")
    public ReturnStatus deleteOrganization(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.woolpert.safe.webservices.SensorMFR>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSensorMFRs", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetSensorMFRs")
    @ResponseWrapper(localName = "getSensorMFRsResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetSensorMFRsResponse")
    public List<SensorMFR> getSensorMFRs();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertSensorMFR", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertSensorMFR")
    @ResponseWrapper(localName = "insertSensorMFRResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertSensorMFRResponse")
    public ReturnStatus insertSensorMFR(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateSensorMFR", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdateSensorMFR")
    @ResponseWrapper(localName = "updateSensorMFRResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdateSensorMFRResponse")
    public ReturnStatus updateSensorMFR(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteSensorMFR", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeleteSensorMFR")
    @ResponseWrapper(localName = "deleteSensorMFRResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeleteSensorMFRResponse")
    public ReturnStatus deleteSensorMFR(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.woolpert.safe.webservices.Sensor>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSensors", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetSensors")
    @ResponseWrapper(localName = "getSensorsResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetSensorsResponse")
    public List<Sensor> getSensors();

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertSensor", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertSensor")
    @ResponseWrapper(localName = "insertSensorResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertSensorResponse")
    public ReturnStatus insertSensor(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        double arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        double arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        double arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        int arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        long arg9);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteSensor", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeleteSensor")
    @ResponseWrapper(localName = "deleteSensorResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeleteSensorResponse")
    public ReturnStatus deleteSensor(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateSensor", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdateSensor")
    @ResponseWrapper(localName = "updateSensorResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdateSensorResponse")
    public ReturnStatus updateSensor(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        double arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        double arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        double arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        int arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        long arg10);

    /**
     * 
     * @return
     *     returns java.util.List<com.woolpert.safe.webservices.Spectrum>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSpectrums", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetSpectrums")
    @ResponseWrapper(localName = "getSpectrumsResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetSpectrumsResponse")
    public List<Spectrum> getSpectrums();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertSpectrum", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertSpectrum")
    @ResponseWrapper(localName = "insertSpectrumResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertSpectrumResponse")
    public ReturnStatus insertSpectrum(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateSpectrum", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdateSpectrum")
    @ResponseWrapper(localName = "updateSpectrumResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdateSpectrumResponse")
    public ReturnStatus updateSpectrum(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteSpectrum", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeleteSpectrum")
    @ResponseWrapper(localName = "deleteSpectrumResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeleteSpectrumResponse")
    public ReturnStatus deleteSpectrum(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.woolpert.safe.webservices.SensorMetadata>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSensorMetadata", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetAllSensorMetadata")
    @ResponseWrapper(localName = "getAllSensorMetadataResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetAllSensorMetadataResponse")
    public List<SensorMetadata> getAllSensorMetadata();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertSensorMetadata", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertSensorMetadata")
    @ResponseWrapper(localName = "insertSensorMetadataResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.InsertSensorMetadataResponse")
    public ReturnStatus insertSensorMetadata(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateSensorMetadata", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdateSensorMetadata")
    @ResponseWrapper(localName = "updateSensorMetadataResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.UpdateSensorMetadataResponse")
    public ReturnStatus updateSensorMetadata(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteSensorMetadata", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeleteSensorMetadata")
    @ResponseWrapper(localName = "deleteSensorMetadataResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.DeleteSensorMetadataResponse")
    public ReturnStatus deleteSensorMetadata(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addSensorToAsset", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.AddSensorToAsset")
    @ResponseWrapper(localName = "addSensorToAssetResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.AddSensorToAssetResponse")
    public ReturnStatus addSensorToAsset(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.woolpert.safe.webservices.Sensor>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSensorsForAsset", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetSensorsForAsset")
    @ResponseWrapper(localName = "getSensorsForAssetResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetSensorsForAssetResponse")
    public List<Sensor> getSensorsForAsset(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.woolpert.safe.webservices.ReturnStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addAssetToSensor", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.AddAssetToSensor")
    @ResponseWrapper(localName = "addAssetToSensorResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.AddAssetToSensorResponse")
    public ReturnStatus addAssetToSensor(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.woolpert.safe.webservices.Asset>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAssetsForSensor", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetAssetsForSensor")
    @ResponseWrapper(localName = "getAssetsForSensorResponse", targetNamespace = "http://webservices.safe.woolpert.com/", className = "com.woolpert.safe.webservices.GetAssetsForSensorResponse")
    public List<Asset> getAssetsForSensor(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
